### ISSUE TITLE
Errors from build-console-for-windows.py

### ISSUE THREAD

**Issue by meldckn** [ensemble-engine/ensemble#75]
Errors are produced when you run `python build-console-for-windows.py` to build the Authoring Tool for Windows (on both Mac and Windows), but a working executable is still produced. 

**Errors when run on macOS 10.14.5:**
```
> python build-console-for-windows.py
Hello, let me make a windows executable of the authoring tool for you today!

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 780, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'authoringTool-Windows.zip' -> 'build/ensemble tool/authoringTool-Windows.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build-console-for-windows.py", line 143, in <module>
    shutil.move(releaseName + ".zip", "build/ensemble tool/" + releaseName +".zip")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 794, in move
    copy_function(src, real_dst)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 426, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 259, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'build/ensemble tool/authoringTool-Windows.zip'
```
**Errors when run on Windows 10 Pro v1903:**
```
> python build-console-for-windows.py
Hello, let me make a windows executable of the authoring tool for you today!
nw.exe
pythonOutput.nw
        1 file(s) copied.
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 566, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'authoringTool-Windows.zip' -> 'build/ensemble tool/authoringTool-Windows.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build-console-for-windows.py", line 143, in <module>
    shutil.move(releaseName + ".zip", "build/ensemble tool/" + releaseName +".zip")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'build/ensemble tool/authoringTool-Windows.zip'
```

**Comment by meldckn** [comment]
Actually, there are no longer any errors since we moved everything to the top level of the repo 🎉
